import Pkg; 
#Pkg.add("Lathe")
#Pkg.add("DataFrames")
#Pkg.add("Plots")
#Pkg.add("GLM")
Pkg.add("StatsBase")
Pkg.add("MLBase") 
Pkg.add("ROCAnalysis") 
Pkg.add("CSV")
Pkg.add("CategoricalArrays")
Pkg.add("FreqTables")
Pkg.add("Random")
println("Successfully imported the packages!!")